//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.22 at 10:31:41 PM CET 
//


package route.traffic.com;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the route.traffic.com package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: route.traffic.com
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTrafficRequest }
     * 
     */
    public GetTrafficRequest createGetTrafficRequest() {
        return new GetTrafficRequest();
    }

    /**
     * Create an instance of {@link GetTrafficResponse }
     * 
     */
    public GetTrafficResponse createGetTrafficResponse() {
        return new GetTrafficResponse();
    }

    /**
     * Create an instance of {@link Traffic }
     * 
     */
    public Traffic createTraffic() {
        return new Traffic();
    }

}
