//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.22 at 10:31:41 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://com.traffic.route", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package route.traffic.com;
