//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.08 at 09:17:14 PM CET 
//
package io.spring.guides.roadclosures;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "routeId",
    "routeName",
    "routeCountry",
    "routeCity",
    "timeClosure",
    "dayClosure",
    "reasonClosure"
})
@XmlRootElement(name = "Road")
public class Road {

    protected long routeId;
    @XmlElement(required = true)
    protected String routeName;
    @XmlElement(required = true)
    protected String routeCountry;
    @XmlElement(required = true)
    protected String routeCity;
    @XmlElement(required = true)
    protected String timeClosure;
    @XmlElement(required = true)
    protected String dayClosure;
    @XmlElement(required = true)
    protected String reasonClosure;

    /**
     * Gets the value of the routeId property.
     * 
     */
    public long getRouteId() {
        return routeId;
    }

    /**
     * Sets the value of the routeId property.
     * 
     */
    public void setRouteId(long value) {
        this.routeId = value;
    }

    /**
     * Gets the value of the routeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteName() {
        return routeName;
    }

    /**
     * Sets the value of the routeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteName(String value) {
        this.routeName = value;
    }

    /**
     * Gets the value of the routeCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteCountry() {
        return routeCountry;
    }

    /**
     * Sets the value of the routeCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteCountry(String value) {
        this.routeCountry = value;
    }

    /**
     * Gets the value of the routeCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteCity() {
        return routeCity;
    }

    /**
     * Sets the value of the routeCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteCity(String value) {
        this.routeCity = value;
    }

    /**
     * Gets the value of the timeClosure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeClosure() {
        return timeClosure;
    }

    /**
     * Sets the value of the timeClosure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeClosure(String value) {
        this.timeClosure = value;
    }

    /**
     * Gets the value of the dayClosure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayClosure() {
        return dayClosure;
    }

    /**
     * Sets the value of the dayClosure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayClosure(String value) {
        this.dayClosure = value;
    }

    /**
     * Gets the value of the reasonClosure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonClosure() {
        return reasonClosure;
    }

    /**
     * Sets the value of the reasonClosure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonClosure(String value) {
        this.reasonClosure = value;
    }

}
